// <auto-generated />
using System;
using AutomationService.Core.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutomationService.Core.Persistence.Migrations
{
    [DbContext(typeof(AutomationDbContext))]
    [Migration("20260826212236_MailSignatur")]
    partial class MailSignatur
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("AutomationService.Features.FormTemplates.Domain.Persistence.FormTemplateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FieldsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WordFilePathMitAuflistung")
                        .HasColumnType("TEXT");

                    b.Property<string>("WordFilePathOhneAuflistung")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FormTemplates");
                });

            modelBuilder.Entity("AutomationService.Features.MailboxMonitor.Domain.Persistence.ReceivedReplyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Absender")
                        .HasColumnType("TEXT");

                    b.Property<string>("Betreff")
                        .HasColumnType("TEXT");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EmpfangenAm")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Quittiert")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Referenz")
                        .HasColumnType("TEXT");

                    b.Property<string>("RohdatenJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rohtext")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VorgangId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WarnungenJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Zugeordnet")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ZuordnungVermutet")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DedupeKey")
                        .IsUnique();

                    b.HasIndex("Referenz");

                    b.ToTable("ReceivedReplies");
                });

            modelBuilder.Entity("AutomationService.Features.Mandanten.Domain.Persistence.MandantEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AktenOrdnernamenJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<string>("Anrede")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAdresse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("TEXT");

                    b.Property<string>("KennzeichenJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notiz")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ort")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Postleitzahl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StrasseHausnummer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefonnummer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Mandanten");
                });

            modelBuilder.Entity("AutomationService.Features.Settings.Domain.Persistence.KanzleiSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abteilung")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AktenStammordner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAdresse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LaufendeAuftragsnummer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MailSignatur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ort")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Personentyp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Postleitzahl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StrasseHausnummer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TabellenkopfFarbeHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefonnummer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("KanzleiSettings");
                });

            modelBuilder.Entity("AutomationService.Features.Versicherer.Domain.Persistence.VersichererEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fax")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameNormalisiert")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ort")
                        .HasColumnType("TEXT");

                    b.Property<string>("Plz")
                        .HasColumnType("TEXT");

                    b.Property<string>("Quelle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Strasse")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ZuletztAktualisiertAm")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NameNormalisiert")
                        .IsUnique();

                    b.ToTable("Versicherer");
                });

            modelBuilder.Entity("AutomationService.Features.Vorgaenge.Domain.Persistence.VorgangEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AbgeschlossenAm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Abteilung")
                        .HasColumnType("TEXT");

                    b.Property<string>("AktenOrdner")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AngefragtAm")
                        .HasColumnType("TEXT");

                    b.Property<string>("AntwortJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("DokumentPfad")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeldWerteJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gegner")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeschaedigtenKennzeichen")
                        .HasColumnType("TEXT");

                    b.Property<string>("Jahr")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kennzeichen")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LaufendeNummer")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MandantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MandantName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PolizeiVorgangsnummer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rechtsgebiet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Referenz")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SchadensaufstellungJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UnfallDatum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unfallort")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unfalluhrzeit")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Jahr");

                    b.HasIndex("MandantId");

                    b.HasIndex("Referenz")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Vorgaenge");
                });
#pragma warning restore 612, 618
        }
    }
}
