// <auto-generated />
using System;
using AutomationService.Core.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutomationService.Core.Persistence.Migrations
{
    [DbContext(typeof(AutomationDbContext))]
    [Migration("20260831172431_VorlagenOrdnerEinstellung")]
    partial class VorlagenOrdnerEinstellung
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("AutomationService.Features.EmailVersand.Domain.Persistence.VersandEintragEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Absender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnhaengeJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Betreff")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmpfaengerJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GesendetAm")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ImGesendetOrdner")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KopieJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("VorgangReferenz")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Weg")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VorgangReferenz");

                    b.ToTable("Versandprotokoll");
                });

            modelBuilder.Entity("AutomationService.Features.FormTemplates.Domain.Persistence.FormTemplateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FieldsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WordFilePathMitAuflistung")
                        .HasColumnType("TEXT");

                    b.Property<string>("WordFilePathOhneAuflistung")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FormTemplates");
                });

            modelBuilder.Entity("AutomationService.Features.MailboxMonitor.Domain.Persistence.ReceivedReplyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Absender")
                        .HasColumnType("TEXT");

                    b.Property<string>("AnhaengeJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Betreff")
                        .HasColumnType("TEXT");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EmpfangenAm")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Quittiert")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Referenz")
                        .HasColumnType("TEXT");

                    b.Property<string>("RohdatenJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rohtext")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VorgangId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WarnungenJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Zugeordnet")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ZuordnungVermutet")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DedupeKey")
                        .IsUnique();

                    b.HasIndex("Referenz");

                    b.ToTable("ReceivedReplies");
                });

            modelBuilder.Entity("AutomationService.Features.Mandanten.Domain.Persistence.MandantEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AktenOrdnernamenJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<string>("Anrede")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAdresse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("TEXT");

                    b.Property<string>("KennzeichenJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notiz")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ort")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Postleitzahl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StrasseHausnummer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefonnummer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Mandanten");
                });

            modelBuilder.Entity("AutomationService.Features.Mandanten.Domain.Persistence.OrdnerStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GesetztAm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ordnername")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ordnername")
                        .IsUnique();

                    b.ToTable("OrdnerStatus");
                });

            modelBuilder.Entity("AutomationService.Features.Sachgebiete.Domain.Persistence.SachgebietEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kuerzel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("RechtsgebietVorschlag")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Sortierung")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Kuerzel")
                        .IsUnique();

                    b.ToTable("Sachgebiete");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aktiv = true,
                            Kuerzel = "C01",
                            Name = "Zivilrecht (allgemein)",
                            RechtsgebietVorschlag = "Zivilrecht",
                            Sortierung = 10
                        },
                        new
                        {
                            Id = 2,
                            Aktiv = true,
                            Kuerzel = "C01a",
                            Name = "Arbeitsrecht",
                            RechtsgebietVorschlag = "Arbeitsrecht",
                            Sortierung = 20
                        },
                        new
                        {
                            Id = 3,
                            Aktiv = true,
                            Kuerzel = "C02",
                            Name = "Familienrecht",
                            RechtsgebietVorschlag = "Familienrecht",
                            Sortierung = 30
                        },
                        new
                        {
                            Id = 4,
                            Aktiv = true,
                            Kuerzel = "C03",
                            Name = "Verkehrsrecht",
                            RechtsgebietVorschlag = "Verkehrsrecht",
                            Sortierung = 40
                        },
                        new
                        {
                            Id = 5,
                            Aktiv = true,
                            Kuerzel = "C03o",
                            Name = "Ordnungswidrigkeitssache",
                            RechtsgebietVorschlag = "Ordnungswidrigkeitssache",
                            Sortierung = 50
                        },
                        new
                        {
                            Id = 6,
                            Aktiv = true,
                            Kuerzel = "C04",
                            Name = "Verkehrsstrafrecht",
                            RechtsgebietVorschlag = "Verkehrsstrafrecht",
                            Sortierung = 60
                        },
                        new
                        {
                            Id = 7,
                            Aktiv = true,
                            Kuerzel = "C05",
                            Name = "Strafrecht",
                            RechtsgebietVorschlag = "Strafrecht",
                            Sortierung = 70
                        },
                        new
                        {
                            Id = 8,
                            Aktiv = true,
                            Kuerzel = "C06",
                            Name = "Verwaltungsrecht",
                            RechtsgebietVorschlag = "Verwaltungsrecht",
                            Sortierung = 80
                        },
                        new
                        {
                            Id = 9,
                            Aktiv = true,
                            Kuerzel = "C06a",
                            Name = "Ausländer- und Asylrecht",
                            RechtsgebietVorschlag = "Ausländer- und Asylrecht",
                            Sortierung = 90
                        },
                        new
                        {
                            Id = 10,
                            Aktiv = true,
                            Kuerzel = "C06s",
                            Name = "Sozialrecht",
                            RechtsgebietVorschlag = "Sozialrecht",
                            Sortierung = 100
                        },
                        new
                        {
                            Id = 11,
                            Aktiv = true,
                            Kuerzel = "C07",
                            Name = "Sonstiges",
                            RechtsgebietVorschlag = "Sonstiges",
                            Sortierung = 110
                        },
                        new
                        {
                            Id = 12,
                            Aktiv = true,
                            Kuerzel = "C07m",
                            Name = "Markenrecht",
                            RechtsgebietVorschlag = "Markenrecht",
                            Sortierung = 120
                        });
                });

            modelBuilder.Entity("AutomationService.Features.Settings.Domain.Persistence.KanzleiSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abteilung")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AktenStammordner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAdresse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LaufendeAuftragsnummer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MailSignatur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MailSignaturHtml")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ort")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Personentyp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Postleitzahl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegisterAblageOrdner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegisterDateiname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegisterExportFilter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RegisterNachAbschlussSchreiben")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StrasseHausnummer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TabellenkopfFarbeHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefonnummer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VorlagenOrdner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("KanzleiSettings");
                });

            modelBuilder.Entity("AutomationService.Features.Settings.Domain.Persistence.StandardSchadenspositionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Betrag")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Reihenfolge")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("StandardSchadenspositionen");
                });

            modelBuilder.Entity("AutomationService.Features.Versicherer.Domain.Persistence.VersichererEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fax")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameNormalisiert")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ort")
                        .HasColumnType("TEXT");

                    b.Property<string>("Plz")
                        .HasColumnType("TEXT");

                    b.Property<string>("Quelle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Strasse")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ZuletztAktualisiertAm")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NameNormalisiert")
                        .IsUnique();

                    b.ToTable("Versicherer");
                });

            modelBuilder.Entity("AutomationService.Features.Vorgaenge.Domain.Persistence.VorgangEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AbgeschlossenAm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Abteilung")
                        .HasColumnType("TEXT");

                    b.Property<string>("AktenOrdner")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AngefragtAm")
                        .HasColumnType("TEXT");

                    b.Property<string>("AntwortJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("DokumentPfad")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntwurfJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeldWerteJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gegner")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeschaedigtenKennzeichen")
                        .HasColumnType("TEXT");

                    b.Property<string>("Jahr")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kennzeichen")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LaufendeNummer")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MandantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MandantName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PolizeiVorgangsnummer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rechtsgebiet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Referenz")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SchadensaufstellungJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UnfallDatum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unfallort")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unfalluhrzeit")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Jahr");

                    b.HasIndex("MandantId");

                    b.HasIndex("Referenz")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Vorgaenge");
                });
#pragma warning restore 612, 618
        }
    }
}
