import "package:flutter/material.dart";

/// Die hellen Farbschemata des Standard-Designs (blaues Material-Theme),
/// aufgeteilt aus `theme.dart`, damit der Theme-Builder dort kurz bleibt.
/// Genutzt werden sie über die Accessor-Methoden von `MaterialTheme`.
abstract final class LightSchemes {
  static ColorScheme standard() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xff0059b5),
      surfaceTint: Color(0xff005cbb),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xff0071e3),
      onPrimaryContainer: Color(0xfffcfbff),
      secondary: Color(0xff030304),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xff1d1d1f),
      onSecondaryContainer: Color(0xff868587),
      tertiary: Color(0xff5b5c60),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xff747479),
      onTertiaryContainer: Color(0xfffefcff),
      error: Color(0xffb2000e),
      onError: Color(0xffffffff),
      errorContainer: Color(0xffdc191d),
      onErrorContainer: Color(0xfffff1ef),
      surface: Color(0xfffcf8f8),
      onSurface: Color(0xff1c1b1b),
      onSurfaceVariant: Color(0xff44474a),
      outline: Color(0xff75777a),
      outlineVariant: Color(0xffc5c6c9),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff313030),
      inversePrimary: Color(0xffabc7ff),
      primaryFixed: Color(0xffd7e2ff),
      onPrimaryFixed: Color(0xff001b3f),
      primaryFixedDim: Color(0xffabc7ff),
      onPrimaryFixedVariant: Color(0xff00458f),
      secondaryFixed: Color(0xffe4e2e4),
      onSecondaryFixed: Color(0xff1b1b1d),
      secondaryFixedDim: Color(0xffc8c6c8),
      onSecondaryFixedVariant: Color(0xff474649),
      tertiaryFixed: Color(0xffe3e2e7),
      onTertiaryFixed: Color(0xff1a1b1f),
      tertiaryFixedDim: Color(0xffc7c6cb),
      onTertiaryFixedVariant: Color(0xff46464b),
      surfaceDim: Color(0xffddd9d9),
      surfaceBright: Color(0xfffcf8f8),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xfff6f3f2),
      surfaceContainer: Color(0xfff1edec),
      surfaceContainerHigh: Color(0xffebe7e7),
      surfaceContainerHighest: Color(0xffe5e2e1),
    );
  }

  static ColorScheme mediumContrast() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xff003570),
      surfaceTint: Color(0xff005cbb),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xff006ad6),
      onPrimaryContainer: Color(0xffffffff),
      secondary: Color(0xff030304),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xff1d1d1f),
      onSecondaryContainer: Color(0xffaaa8aa),
      tertiary: Color(0xff35363a),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xff6c6d71),
      onTertiaryContainer: Color(0xffffffff),
      error: Color(0xff740006),
      onError: Color(0xffffffff),
      errorContainer: Color(0xffd8151b),
      onErrorContainer: Color(0xffffffff),
      surface: Color(0xfffcf8f8),
      onSurface: Color(0xff111111),
      onSurfaceVariant: Color(0xff343639),
      outline: Color(0xff505355),
      outlineVariant: Color(0xff6b6d70),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff313030),
      inversePrimary: Color(0xffabc7ff),
      primaryFixed: Color(0xff006ad6),
      onPrimaryFixed: Color(0xffffffff),
      primaryFixedDim: Color(0xff0053a9),
      onPrimaryFixedVariant: Color(0xffffffff),
      secondaryFixed: Color(0xff6e6c6f),
      onSecondaryFixed: Color(0xffffffff),
      secondaryFixedDim: Color(0xff555457),
      onSecondaryFixedVariant: Color(0xffffffff),
      tertiaryFixed: Color(0xff6c6d71),
      onTertiaryFixed: Color(0xffffffff),
      tertiaryFixedDim: Color(0xff545459),
      onTertiaryFixedVariant: Color(0xffffffff),
      surfaceDim: Color(0xffc9c6c5),
      surfaceBright: Color(0xfffcf8f8),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xfff6f3f2),
      surfaceContainer: Color(0xffebe7e7),
      surfaceContainerHigh: Color(0xffdfdcdc),
      surfaceContainerHighest: Color(0xffd4d1d0),
    );
  }

  static ColorScheme highContrast() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xff002b5e),
      surfaceTint: Color(0xff005cbb),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xff004794),
      onPrimaryContainer: Color(0xffffffff),
      secondary: Color(0xff030304),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xff1d1d1f),
      onSecondaryContainer: Color(0xffd4d1d4),
      tertiary: Color(0xff2b2c30),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xff48494d),
      onTertiaryContainer: Color(0xffffffff),
      error: Color(0xff600004),
      onError: Color(0xffffffff),
      errorContainer: Color(0xff98000a),
      onErrorContainer: Color(0xffffffff),
      surface: Color(0xfffcf8f8),
      onSurface: Color(0xff000000),
      onSurfaceVariant: Color(0xff000000),
      outline: Color(0xff2a2c2f),
      outlineVariant: Color(0xff47494c),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff313030),
      inversePrimary: Color(0xffabc7ff),
      primaryFixed: Color(0xff004794),
      onPrimaryFixed: Color(0xffffffff),
      primaryFixedDim: Color(0xff00316a),
      onPrimaryFixedVariant: Color(0xffffffff),
      secondaryFixed: Color(0xff49494b),
      onSecondaryFixed: Color(0xffffffff),
      secondaryFixedDim: Color(0xff333234),
      onSecondaryFixedVariant: Color(0xffffffff),
      tertiaryFixed: Color(0xff48494d),
      onTertiaryFixed: Color(0xffffffff),
      tertiaryFixedDim: Color(0xff313237),
      onTertiaryFixedVariant: Color(0xffffffff),
      surfaceDim: Color(0xffbbb8b8),
      surfaceBright: Color(0xfffcf8f8),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xfff4f0ef),
      surfaceContainer: Color(0xffe5e2e1),
      surfaceContainerHigh: Color(0xffd7d4d3),
      surfaceContainerHighest: Color(0xffc9c6c5),
    );
  }
}
